---
abstract: 'An extension to IPC::Open3 that will feed out and err to callbacks instead of requiring the caller to handle them.'
author:
  - 'Lucas Theisen <lucastheisen@pastdev.com>'
  - 'Alceu Rodrigues de Freitas Junior <arfreitas@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IPC-Open3-Callback
requires:
  IPC::Open3: '0'
resources:
  homepage: https://github.com/lucastheisen/ipc-open3-callback
  repository: https://github.com/lucastheisen/ipc-open3-callback.git
version: '1.13'
